---
Name: 'leochenftw-ss-arsenal'
---
SilverStripe\Assets\File:
  extensions:
    - Leochenftw\Extension\FileExtension
gorriecoe\Link\Models\Link:
  extensions:
    - Leochenftw\Extension\LinkExtension
SilverStripe\Assets\Image:
  extensions:
    - Leochenftw\Extension\ImageExtension
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Leochenftw\Extension\SearchableExtension
    - Leochenftw\Extension\MetaExtension
    - Leochenftw\Extension\SocialTagExtension
SilverStripe\Security\Member:
  extensions:
    - Leochenftw\Extension\MemberExtension
SilverStripe\ORM\DataList:
  extensions:
    - Leochenftw\Extension\DataListExtension
SilverStripe\ORM\ArrayList:
  extensions:
    - Leochenftw\Extension\DataListExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Leochenftw\Extension\SiteConfigExtension
    - Leochenftw\Extension\GAFamilyExtension
    - Leochenftw\Extension\SocialTagExtension
